Changes into SecurityProvider interface and Logout middleware
genexuslabs/DotNetClasses pull request #757
Opened 2023-01-26 13:30 UTC by MBarnech

2023-01-26 14:42 UTC, anaiberta requested changes

2023-01-26 14:42 UTC, anaiberta commented on dotnet/src/dotnetframework/GxClasses/Security/GxSecurityProvider.cs
> +		void oauthlogout(IGxContext context, out String URL, out short statusCode);
Compatibility issue: cannot change the method signature; we must preserve the older version (defining it as obsolete if it required).

2023-01-26 21:18 UTC, claudiamurialdo approved these changes

2023-01-26 21:21 UTC, claudiamurialdo requested changes

2023-01-26 21:21 UTC, claudiamurialdo commented on dotnet/src/dotnetframework/GxClasses/Middleware/GXHttpServices.cs
> +				if (statusCode == 303)
Instead of statusCode==303,  statusCode== (int)HttpStatusCode.SeeOther coud be used.

2023-03-10 13:17 UTC, claudiamurialdo approved these changes

2023-03-14 14:16 UTC, anaiberta approved these changes

2023-03-14 14:32 UTC, merged